// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gorm} from '../models';

export function CheckAuth():Promise<boolean>;

export function Greet(arg1:string):Promise<string>;

export function InitDatabase():Promise<gorm.DB>;

export function SaveCredentials(arg1:string,arg2:string):Promise<boolean>;

export function SetNotification(arg1:string):Promise<void>;
