// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAuth() {
  return window['go']['backend']['App']['CheckAuth']();
}

export function GetList() {
  return window['go']['backend']['App']['GetList']();
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function InitDatabase() {
  return window['go']['backend']['App']['InitDatabase']();
}

export function SaveCredentials(arg1, arg2) {
  return window['go']['backend']['App']['SaveCredentials'](arg1, arg2);
}

export function SetNotification(arg1) {
  return window['go']['backend']['App']['SetNotification'](arg1);
}
